# Generated by Django 5.2.5 on 2025-08-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('reporter', 'Reporter'), ('reader', 'Reader')], default='reader', max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
