# Generated by Django 5.2.5 on 2025-08-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('author', 'author'), ('reporter', 'Reporter'), ('reader', 'Reader')], default='reader', max_length=20),
        ),
    ]
