# Generated by Django 5.2.5 on 2025-08-12 12:46

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/')),
                ('title', models.CharField(max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft')], default='DRF', max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notices/images/')),
                ('title', models.CharField(max_length=255)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('DRF', 'Draft')], default='DRF', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
