# Generated by Django 5.2.5 on 2025-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_report_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
