# Generated by Django 5.2.5 on 2025-08-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_report_message_report_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
